import './globals.css'
import 'modern-css-reset'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import localFont from 'next/font/local'
import { ThemeProvider } from 'next-themes'

import Header from '@/app/components/header'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const geist = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 400 500 900',
})

export const metadata: Metadata = {
  title: {
    template: '%s - Yamato Handai',
    default: 'My homepage - Yamato Handai',
  },
  description: 'My homepage generated by Next.js with microCMS',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={clsx(geist.variable, montserrat.variable)} suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
