import './globals.css'
import 'modern-css-reset'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { M_PLUS_Rounded_1c } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

import Header from '@/app/components/header'

const mplus = M_PLUS_Rounded_1c({
  variable: '--font-mplus',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: {
    template: '%s - Yamato Handai',
    default: 'My homepage - Yamato Handai',
  },
  description: 'My homepage generated by Next.js with microCMS',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={clsx(mplus.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
